apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: epicheck-storage
    labels:
        app: epicheck
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
    storageClassName: standard # Change based on your cloud provider
